// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_M7T5KJhG-CY_eBCm0wAPyqlJ6_HE6O0',
    appId: '1:2401661222:web:962a2f6b2dc1d0612911e7',
    messagingSenderId: '2401661222',
    projectId: 'biz-alert',
    authDomain: 'biz-alert.firebaseapp.com',
    storageBucket: 'biz-alert.appspot.com',
    measurementId: 'G-1HN8PYX6ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFdL6LhqG89ua4dqbK93CYj-dF_3wUPY8',
    appId: '1:2401661222:android:b97f8282332b50712911e7',
    messagingSenderId: '2401661222',
    projectId: 'biz-alert',
    storageBucket: 'biz-alert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHgF78VvRZB0l6kLqk6LFPL4KkjK9wNyM',
    appId: '1:2401661222:ios:ca262144f2f38e762911e7',
    messagingSenderId: '2401661222',
    projectId: 'biz-alert',
    storageBucket: 'biz-alert.appspot.com',
    androidClientId: '2401661222-la99csn1m1qd7b6fs9rrrua437c6sa56.apps.googleusercontent.com',
    iosClientId: '2401661222-e4ugmnfaki9o4bpi71kjsddqjuoq1r08.apps.googleusercontent.com',
    iosBundleId: 'com.example.bizAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHgF78VvRZB0l6kLqk6LFPL4KkjK9wNyM',
    appId: '1:2401661222:ios:ca262144f2f38e762911e7',
    messagingSenderId: '2401661222',
    projectId: 'biz-alert',
    storageBucket: 'biz-alert.appspot.com',
    androidClientId: '2401661222-la99csn1m1qd7b6fs9rrrua437c6sa56.apps.googleusercontent.com',
    iosClientId: '2401661222-e4ugmnfaki9o4bpi71kjsddqjuoq1r08.apps.googleusercontent.com',
    iosBundleId: 'com.example.bizAlert',
  );
}
